version: '3'
services:
  alpha:
    container_name: alpha-svc
    build:
      context: .
      dockerfile: ./apps/alpha/Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - fastify-postgres-template

  # Setup Postgres Database
  fastify-postgres-db:
    container_name: fastify-template-postgres
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # This will persist the data on host machine remember
      # it will be there as long as the volume is there essentially
      # don't pass the `-v` flag to docker-compose down.
      - fastify-postgres:/var/lib/postgresql/data
    networks:
      - fastify-postgres-template

  # Setup PGAdmin for Postgres
  fastify-pgadmin:
    container_name: fastify-template-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - fastify-pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    networks:
      - fastify-postgres-template

  # Setup Redis key-value store
  fastify-redis:
    container_name: fastify-template-cache
    image: 'redis'
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', 'fastify_redis_password']
    volumes:
      - fastify_redis_data:/data
      - fastify_redis_conf:/usr/local/etc/redis/redis.conf

# Volumes that the compose uses will be used to persist
# for our database persistance.
volumes:
  fastify-postgres: {}
  fastify-pgadmin: {}
  fastify_redis_data: {}
  fastify_redis_conf: {}

# Networks used by docker-compose and all the apps in it
networks:
  fastify-postgres-template:
    driver: bridge
