version: '3'
services:
  # ------------------------- ALPHA -------------------------
  alpha-postgres-db:
    container_name: fp-alpha-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - fp-alpha-db:/var/lib/postgresql/data

  alpha-pgadmin:
    container_name: fp-alpha-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - fp-alpha-pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    expose:
      - '5050'
    restart: unless-stopped

  alpha-redis:
    container_name: fp-alpha-cache
    image: 'redis'
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', 'fastify_redis_password']
    volumes:
      - fp-alpha-cache-data:/data
      - fp-alpha-cache-conf:/usr/local/etc/redis/redis.conf
  # xxxxxxxxxxxxxxxxxxxxxxxxxx ALPHA xxxxxxxxxxxxxxxxxxxxxxxxxx

  # ------------------------- KEYCLOAK -------------------------
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ['start-dev', '--metrics-enabled=true', '--http-port 8080']
    environment:
      ## https://www.keycloak.org/server/all-config
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password123
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_URL_HOST: '0.0.0.0'
      KC_PROXY: 'passthrough'
    ports:
      - '8080:8080'
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    container_name: 'keycloak-postgres'
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
      - ./init/keycloak_db:/docker-entrypoint-initdb.d/
  # xxxxxxxxxxxxxxxxxxxxxxxxxx KEYCLOAK xxxxxxxxxxxxxxxxxxxxxxxxxx

# Volumes for services
volumes:
  # ------- ALPHA -------
  fp-alpha-db: {}
  fp-alpha-pgadmin: {}
  fp-alpha-cache-data: {}
  fp-alpha-cache-conf: {}
  # xxxxxxx ALPHA xxxxxxx
  keycloak-postgres:
    driver: local
