apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.secrets.name }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.secrets.keycloakAdmin }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.secrets.keycloakAdminPassword }}
  KC_HTTPS_CERTIFICATE_FILE: {{ .Values.keycloak.secrets.kcHttpsCertFile }}
  KC_HTTPS_CERTIFICATE_KEY_FILE: {{ .Values.keycloak.secrets.kcHttpsCertKeyFile }}
  KC_HEALTH_ENABLED: "{{ .Values.keycloak.secrets.kcHealthEnabled }}"
  KC_METRICS_ENABLED: "{{ .Values.keycloak.secrets.kcMetricsEnabled }}"
  KC_HOSTNAME: {{ .Values.keycloak.secrets.kcHostName }}
  KC_PROXY: {{ .Values.keycloak.secrets.kcProxy }}
  KC_DB: {{ .Values.keycloak.secrets.kcDb }}
  KC_DB_URL: {{ .Values.keycloak.secrets.kcDbUrl }}
  jgroups.dns.query: {{ .Values.keycloak.secrets.jgroupsDnsQuery }}
