apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.keycloak.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - fake
      secretName: {{ .Values.keycloak.tls.secretName }}
  rules:
  - host: "auth.localtest.me"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.keycloak.metadata.name }}
            port:
              number: 443
