apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.secrets.name }}
type: Opaque
stringData:
  NODE_ENV: {{ .Values.application.nodeEnv }}
  PORT: "{{ .Values.application.containerPort }}"
  # App Database Config
  DB_DIALECT: {{ .Values.application.database.dialect }}
  DB_DATABASE: {{ .Values.application.database.name }}
  DB_HOST: {{ .Values.application.database.host }}
  DB_PORT: "{{ .Values.application.database.port }}"
  # App Redis Config
  REDIS_HOST: {{ .Values.application.cache.host }}
  REDIS_PORT: "{{ .Values.application.cache.port }}"
  REDIS_USER: {{ .Values.application.cache.user }}
  REDIS_PASSWORD: {{ .Values.application.cache.password }}
