name: Alpha Service CI

# CI for Alpha Service, this will trigger on any pushes that were made
# to the branch with any changes happeneing in the `alpha` directory
on:
  push:
    branches: [main]
    paths:
      - 'apps/alpha/**'
      - .github/workflow/alpha-ci.yml
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # We'll test against both 16 Gallium LTS.
    # And the current LTS that's Node 18, to be honest
    # the reason we wanna do this is because of a lot of trouble
    # we've faced with migrating from Node 16 to Node 18.
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          # Trying with the one on root, TurboRepo doesn't generate
          # any lockfiles within subdirs of any apps!
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the `alpha` app
        run: pnpm run build
        working-directory: ./apps/alpha

      # For now we'll only run Unit tests on CI
      # TODO: Write and wire up integration tests for CI
      - name: Test the `alpha` app
        run: pnpm run test:unit
        working-directory: ./apps/alpha
